name: cham_ly_thuyet
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: 0.20.2 
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.1
  path: ^1.9.1
  fl_chart: ^1.0.0
  google_fonts: ^6.1.0
  flutter_local_notifications: ^14.0.0
  flutter_email_sender: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/l10n/
    - assets/images/
    - assets/icon/
    - assets/